### ISSUE TITLE
can we use this in ct images?

### ISSUE THREAD

**Issue by argman** [uncbiag/PStrip#2]

**Comment by marcniethammer** [comment]
It currently works for T1-weighted MR images (as this is the MR sequence for the atlas and the sequence from which the PCA basis was created).

That being said, given a CT atlas image and a number of corresponding CT images to train the atlas model from one could adapt the method so that it would work for CT. 

This is mostly a data availability issue (we have not looked into it at this point). The algorithm itself should transfer.
